KEY_CAMERA = "camera"
KEY_VIDEO_SIZE = "video_size"
KEY_PHOTO_SIZE = "photo_size"

DEFAULT_VIDEO_SIZE = "1920x1080"

KEY_VIDEO_FPS = "video_fps"
KEY_VIDEO_BITRATE = "video_bitrate"
KEY_CAMERA_MODE_STR = "camera_mode_str"
KEY_VIDEO_WIDTH = "video_width"
KEY_VIDEO_HEIGHT = "video_height"

DEFAULT_VIDEO_FPS = 15
DEFAULT_VIDEO_BITRATE = 4000000
DEFAULT_CAMERA_MODE_STR = "1920:1080"
DEFAULT_VIDEO_WIDTH = 1920
DEFAULT_VIDEO_HEIGHT = 1080

KEY_HFLIP = "hflip"
KEY_VFLIP = "vflip"
KEY_SCREENSHOT = "screenshot"

DEFAULT_HFLIP = False
DEFAULT_VFLIP = False
DEFAULT_SCREENSHOT = True

KEY_STREAM_CAMERA_MODE_STR = "stream_camera_mode_str"
KEY_STREAM_VIDEO_WIDTH = "stream_video_width"
KEY_STREAM_VIDEO_HEIGHT = "stream_video_height"

DEFAULT_STREAM_CAMERA_MODE_STR = "1280:720"
DEFAULT_STREAM_VIDEO_WIDTH = 1280
DEFAULT_STREAM_VIDEO_HEIGHT = 720
