locale: en

path:
  jpeg: /mnt/data/videoreg/jpeg
  h264: /mnt/data/videoreg/h264
  mp4: /mnt/data/videoreg/mp4
  jpeg_fave: /mnt/data/videoreg/jpeg_fave
  h264_fave: /mnt/data/videoreg/h264_fave

services:
  - name: vrg-core
    plugins:
      - org_vrg_core
      - org_vrg_bus
      - org_vrg_net
      - org_vrg_power
      - org_vrg_stat
  - name: vrg-camera
    plugins:
      - org_vrg_camera
  - name: vrg-modem
    plugins:
      - org_vrg_gps
      - org_vrg_sms
  - name: vrg-http
    plugins:
      - org_vrg_http
  - name: vrg-bot
    plugins:
      - org_vrg_bot
      - org_vrg_botvk
  - name: vrg-pisugar-watchdog
    plugins: []
  - name: vrg-mediamtx
    plugins: []

plugins:
  - id: org_vrg_core
    name: core
    enabled: true

  - id: org_vrg_bus
    name: bus
    enabled: true

  - id: org_vrg_net
    name: net
    enabled: true

  - id: org_vrg_power
    name: power
    enabled: true

  - id: org_vrg_stat
    name: stat
    enabled: true

  - id: org_vrg_camera
    name: camera
    enabled: true
    pages:
      - url: feed
        menu: Лента
        component: MediaFeedComponent.js

      - url: camera
        menu: Камера
        component: CameraComponent.js

  - id: org_vrg_bot
    name: bot
    enabled: true

  - id: org_vrg_botvk
    name: botvk
    enabled: true

  - id: org_vrg_http
    name: http
    enabled: true

  - id: org_vrg_gps
    name: gps
    enabled: true

  - id: org_vrg_sms
    name: sms
    enabled: true

interfaces:
  - name: bot
    interactions:
      text: bot.send_text
      edit_text: bot.edit_message
      status: bot.send_status
      image: bot.send_image
      video: bot.send_video
      document: bot.send_document

  - name: botvk
    list_page_size: 3 # VK inline keyboards allow at most 6 rows / 10 buttons
    interactions:
      text: botvk.send_text
      edit_text: botvk.edit_message
      status: botvk.send_status
      image: botvk.send_image
      document: botvk.send_document

  - name: sms
    interactions:
      text: sms.send_text
