"""Assembling plugin Vue components into a single `bundle.js`.

Plugin components live in `plugins/<id>/http/components/`. Rather than loading
each via its own `<script>`, the components declared in every plugin's
`manifest.yaml` `http.components` list are concatenated into
`static/js/bundle.js`, served as an ordinary static file.
"""

from pathlib import Path

from plugins.org_vrg_http.manifest_reader import read_plugin_http_configs


def build_bundle(plugins_dir: Path, out_path: Path) -> int:
  """Concatenate all plugin component files into `out_path` (overwrite).

  Args:
    plugins_dir: path to the `plugins` directory.
    out_path: target path for the generated `bundle.js`.

  Returns:
    The number of component files written into the bundle.
  """
  configs = read_plugin_http_configs(plugins_dir)

  parts: list[str] = ["// AUTO-GENERATED by org_vrg_http bundle.py — do not edit.\n"]
  count = 0

  # org_vrg_http's own shared components (formerly loaded via individual <script>
  # tags in index.html). Base UI components first, then page components — pages
  # (and plugin components below) reference base components like `Icon` at
  # definition time (`components: { Icon, ... }`), so order matters.
  http_components_dir = (
    plugins_dir / "org_vrg_http" / "static" / "js" / "components"
  )
  http_files = sorted(http_components_dir.glob("*.js"))
  http_files += sorted(http_components_dir.glob("pages/*.js"))
  for file_path in http_files:
    rel = file_path.relative_to(http_components_dir)
    parts.append(f"\n// --- org_vrg_http/{rel} ---\n")
    parts.append(file_path.read_text(encoding="utf-8"))
    count += 1

  for config in configs:
    plugin_id = config["id"]
    components = config["http"].get("components") or []
    components_dir = plugins_dir / plugin_id / "http" / "components"

    for filename in components:
      file_path = components_dir / filename
      if not file_path.is_file():
        continue
      parts.append(f"\n// --- {plugin_id}/{filename} ---\n")
      parts.append(file_path.read_text(encoding="utf-8"))
      count += 1

  out_path.parent.mkdir(parents=True, exist_ok=True)
  out_path.write_text("\n".join(parts), encoding="utf-8")

  return count
