KEEP_ALIVE_WAIT_NETWORK_KEY = "wait_network"
KEEP_ALIVE_WAIT_NETWORK_SEC = 20

KEEP_ALIVE_WAIT_USER_INTERACTION_KEY = "wait_user_interaction"
KEEP_ALIVE_WAIT_USER_INTERACTION_SEC = 60

KEEP_ALIVE_WAIT_FINISH_OUTCOME_REQUEST_KEY = "wait_finish_outcome_request"

TIMEOUT_SEND_MESSAGE = 10
TIMEOUT_SEND_PHOTO = 60
TIMEOUT_SEND_VIDEO = 120
TIMEOUT_SEND_DOCUMENT = 120
